#!/usr/bin/perl

$uu=scalar(@ARGV);

if ($uu ne 4)
{
    print "CreateHCUTS is used as\n";
    print "./CreateHCUTS [SetFile] [PartitionFile] [m] [n]\n\n";
    print "with [SubsetFile] the list of m+1 subset of Vn";
    print "with [PartitionFile] a list of m+1 partitions of Vn";
    print "with [m] indicating the order of the supermetric\n";
    print "with [n] the size of the set on which we consider the supermetric\n";
    die;
}

$SetFile=$ARGV[0];
$PartitionFile=$ARGV[1];
$m=$ARGV[2];
$n=$ARGV[3];


$k=$m+1;
open(INFILE, $SetFile) or die "impossible to open ".$SetFile;
@SET=<INFILE>;
close(INFILE);
$Cnk=scalar(@SET);

open(INFILE, $PartitionFile) or die "impossible to open ".$PartitionFile;
@PART=<INFILE>;
close(INFILE);

for ($iPart=1; $iPart<=scalar(@PART); $iPart++)
{
    $line=$PART[$iPart-1];
    @LE=split("#", $line);
    for ($iLE=1; $iLE<=scalar(@LE); $iLE++)
    {
	@S=split(" ", $LE[$iLE-1]);
	for ($iS=1; $iS<=scalar(@S); $iS++)
	{
	    $POS[$S[$iS-1]]=$iLE;
	}
    }
    print " 0";
    for ($iSet=1; $iSet<=scalar(@SET); $iSet++)
    {
	@set=split(" ", $SET[$iSet-1]);
	for ($iO=1; $iO<=$k; $iO++)
	{
	    $K[$iO]="NO";
	}
	$TEST=1;
	for ($iPos=1; $iPos<=$n; $iPos++)
	{
	    if ($set[$iPos-1] eq 1)
	    {
		$iOrb=$POS[$iPos];
		if ($K[$iOrb] eq "NO")
		{
		    $K[$iOrb]="YES";
		}
		else
		{
		    $TEST=0;
		}
	    }
	}
	if ($TEST eq 1)
	{
	    print " 1";
	}
	else
	{
	    print " 0";
	}
    }
    print "\n";
}

