#!/usr/bin/perl

# we take a list of oriented partitions as input and return as output 
# the corresponding oriented multicut


while (<>)
{
    $line=$_;
    @U=split(" ", $line);
    # determine the integer $k$
    @SPS=split("#", $line);
    $k=scalar(@SPS);
    # determine size of partitioned set
    $size=scalar(@U)-$k+1;

    print " 0";
    for ($i=1; $i<=$size; $i++)
    {
	for ($j=1; $j<=$size; $j++)
	{
	    if ($i ne $j)
	    {
		$h=0;
		$iter=1;
		while (1)
		{
		    if ($U[$iter-1] eq "#")
		    {
			$h++;
		    }
		    if ($U[$iter-1] eq $i)
		    {
			last;
		    }
		    $iter++;
		}
		$k=0;
		$iter=1;
		while (1)
		{
		    if ($U[$iter-1] eq "#")
		    {
			$k++;
		    }
		    if ($U[$iter-1] eq $j)
		    {
			last;
		    }
		    $iter++;
		}
		if ($h < $k)
		{
		    print " 1";
		}
		else
		{
		    print " 0";
		}
	    }

	}
    }
    print "\n";
}
